### ISSUE TITLE
plugin.php appears to be doubled.

### ISSUE THREAD

**Issue by nate2014jatc** [joshp23/YOURLS-PUNS#3]
Hello,
I tried to active your really neat plugin today (01.30.2020) and I got the following PHP error;
```
2020/01/30 10:28:51 [error] 550#550: *3419 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '<', expecting end of file in /var/www/html/YOURLS/user/plugins/puns/plugin.php on line 447" while reading response header from upstream
```
So I opened up the file, checked what was going on at Line 447, and it looked like the file had started over for some reason!
I check you master branch, and it appears that this is the case there too, but you last commit didn't have this file being ~890 lines long.

I Tried cutting out the "extra" part, and now I can get your plugin to activate on my admin dashboard.

**Comment by joshp23** [comment]
wow, been away for a while. fixed. thanks.
